# Docker compose file to aid developers to test prysm VCs in a distributed validator cluster.
version: "3.8"

services:
  #                                   _                                                  _      
  #  _ __  _ __ _   _ ___ _ __ ___   | |__   ___  __ _  ___ ___  _ __    _ __   ___   __| | ___ 
  # | '_ \| '__| | | / __| '_ ` _ \  | '_ \ / _ \/ _` |/ __/ _ \| '_ \  | '_ \ / _ \ / _` |/ _ \
  # | |_) | |  | |_| \__ \ | | | | | | |_) |  __/ (_| | (_| (_) | | | | | | | | (_) | (_| |  __/
  # | .__/|_|   \__, |___/_| |_| |_| |_.__/ \___|\__,_|\___\___/|_| |_| |_| |_|\___/ \__,_|\___|
  # |_|         |___/                                                  
  prysm:
    image: prysmaticlabs/prysm-beacon-chain:${PRYSM_VERSION:-v3.2.1}
    ports:
      - ${PRYSM_PORT_P2P_TCP:-13000}:13000/tcp # P2P TCP
      - ${PRYSM_PORT_P2P_UDP:-12000}:12000/udp # P2P UDP
    command: |
      --execution-endpoint=${PRYSM_EXECUTION_ENDPOINT:-http://nethermind:8551}
      --goerli 
      --jwt-secret=/home/jwt/jwt.hex 
      --genesis-state=/home/prysm/genesis.ssz 
      --accept-terms-of-use 
      --checkpoint-sync-url=https://goerli.checkpoint-sync.ethdevops.io
      --rpc-host="0.0.0.0"
      --grpc-gateway-host="0.0.0.0"
    networks: [ cluster ]
    volumes:
      - ./prysm:/home/prysm
      - ./jwt:/home/jwt
    restart: unless-stopped

  #                                              _ _     _       _                 
  #  _ __  _ __ _   _ ___ _ __ ___   __   ____ _| (_) __| | __ _| |_ ___  _ __ ___ 
  # | '_ \| '__| | | / __| '_ ` _ \  \ \ / / _` | | |/ _` |/ _` | __/ _ \| '__/ __|
  # | |_) | |  | |_| \__ \ | | | | |  \ V / (_| | | | (_| | (_| | || (_) | |  \__ \
  # | .__/|_|   \__, |___/_| |_| |_|   \_/ \__,_|_|_|\__,_|\__,_|\__\___/|_|  |___/
  # |_|         |___/                                                              
  vc0-prysm:
    build: prysm
    platform: "linux/amd64"
    networks: [ cluster ]
    depends_on: [ node0, prysm ]
    restart: unless-stopped
    environment:
      BEACON_NODE_ADDRESS: "http://node0:3600"
      GRPC_BN: "prysm:4000"
    volumes:
      - ./prysm:/home/prysm
      - .charon/cluster/node0/validator_keys:/home/charon/validator_keys
  
  vc1-prysm:
    build: prysm
    platform: "linux/amd64"
    networks: [ cluster ]
    depends_on: [ node1, prysm ]
    restart: unless-stopped
    environment:
      BEACON_NODE_ADDRESS: "http://node1:3600"
      GRPC_BN: "prysm:4000"
    volumes:
      - ./prysm:/home/prysm
      - .charon/cluster/node1/validator_keys:/home/charon/validator_keys

  vc2-prysm:
    build: prysm
    platform: "linux/amd64"
    networks: [ cluster ]
    depends_on: [ node2, prysm ]
    restart: unless-stopped
    environment:
      BEACON_NODE_ADDRESS: "http://node2:3600"
      GRPC_BN: "prysm:4000"
    volumes:
      - ./prysm:/home/prysm
      - .charon/cluster/node2/validator_keys:/home/charon/validator_keys

  vc3-prysm:
    build: prysm
    platform: "linux/amd64"
    networks: [ cluster ]
    depends_on: [ node3, prysm ]
    restart: unless-stopped
    environment:
      BEACON_NODE_ADDRESS: "http://node3:3600"
      GRPC_BN: "prysm:4000"
    volumes:
      - ./prysm:/home/prysm
      - .charon/cluster/node3/validator_keys:/home/charon/validator_keys

  vc4-prysm:
    build: prysm
    platform: "linux/amd64"
    networks: [ cluster ]
    depends_on: [ node4, prysm ]
    restart: unless-stopped
    environment:
      BEACON_NODE_ADDRESS: "http://node4:3600"
      GRPC_BN: "prysm:4000"
    volumes:
      - ./prysm:/home/prysm
      - .charon/cluster/node4/validator_keys:/home/charon/validator_keys

  vc5-prysm:
    build: prysm
    platform: "linux/amd64"
    networks: [ cluster ]
    depends_on: [ node5, prysm ]
    restart: unless-stopped
    environment:
      BEACON_NODE_ADDRESS: "http://node5:3600"
      GRPC_BN: "prysm:4000"
    volumes:
      - ./prysm:/home/prysm
      - .charon/cluster/node5/validator_keys:/home/charon/validator_keys