version: "3.8"

services:
  node0:
    image: ghcr.io/obolnetwork/charon/charon:latest
    entrypoint: /charon/run.sh
    networks: [cluster]
    user: root
    volumes:
      - .:/charon
    working_dir: /charon/node0

  node1:
    extends:
      service: node0
    working_dir: /charon/node1
    environment:
      - BOOTNODE=node0

  node2:
    extends:
      service: node0
    working_dir: /charon/node2
    environment:
      - BOOTNODE=node0

  node3:
    extends:
      service: node0
    working_dir: /charon/node3
    environment:
      - BOOTNODE=node0

networks:
  cluster: