version: "3.8"

x-node-base: &node-base
  image: ghcr.io/obolnetwork/charon/charon:v0.2.0
  entrypoint: /charon/run.sh
  networks: [ cluster ]
  volumes:
    - .:/charon

services:
  node0:
    <<: *node-base
    working_dir: /charon/node0
    environment:
      GENERATE: "true"
      CLEAN: "${CLEAN:-true}"
      SIMNET_VMOCK: "false" # Uses Lighthouse VC
    ports:
      - "16002:16002"

  node1:
    <<: *node-base
    working_dir: /charon/node1
    environment:
      SIMNET_VMOCK: "false" # Uses Teku VC

  node2:
    <<: *node-base
    working_dir: /charon/node2

  node3:
    <<: *node-base
    working_dir: /charon/node3

  bootnode:
    <<: *node-base
    image: ghcr.io/obolnetwork/charon/charon:latest # TODO(corver): Remove this once version above supports bootnode.
    working_dir: /charon/bootnode
    entrypoint: /charon/bootnode/run.sh

  vc0-lh:
    build: lighthouse
    networks: [cluster]
    environment:
      NODE: node0
    volumes:
     - .:/charon

  vc1-teku:
    image: consensys/teku:latest
    networks: [cluster]
    entrypoint: [/charon/teku/run.sh]
    environment:
      NODE: node1
    volumes:
     - .:/charon

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks: [cluster]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks: [cluster]
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/simnet_dash.json:/etc/dashboards/simnet_dash.json

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks: [cluster]
    ports:
      - "16686:16686"

networks:
  cluster:
