version: "3.8"

x-node-base: &node-base
  image: ghcr.io/obolnetwork/charon/charon:latest
  entrypoint: /charon/run.sh
  networks: [ cluster ]
  volumes:
    - .:/charon

services:
  node0:
    <<: *node-base
    working_dir: /charon/node0
    environment:
      GENERATE: "true"
      CLEAN: "${CLEAN:-true}"

  node1:
    <<: *node-base
    working_dir: /charon/node1
    environment:
      BOOTNODE: node0

  node2:
    <<: *node-base
    working_dir: /charon/node2
    environment:
      BOOTNODE: node0

  node3:
    <<: *node-base
    working_dir: /charon/node3
    environment:
      BOOTNODE: node0

  prometheus:
    image: prom/prometheus:latest
    user: root
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    networks: [cluster]
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

networks:
  cluster:
