{
 "title": "Local Docker Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node start time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_start_time_secs * 1000", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Charon Node Observed Slot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "core_scheduler_current_slot", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Beacon Node Latency",
   "type": "graph",
   "description": "Total request length / Total number of requests made to beacon nodes by charon clients",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "app_eth2_latency_seconds_sum / app_eth2_latency_seconds_count",
     "legendFormat": "{{job}}-{{endpoint}}"
    }
   ]
  }
 ]
}